"""Every prose copy of a Racket fidelity number matches the committed run.

``benchmarks/racket_fidelity/results.json`` is regenerated by
``run_fidelity.py``; the coverage figure and its neighbours are then RESTATED
in two documents that no tool rewrites. Nothing bound them together, so
#549 could move ``source_coverage_pct`` 86.2 -> 86.5 in the artifact and leave
both prose copies reading 86.2 with a green suite.

⚠ The rows are checked, not only the headline. A ratchet that asserts the
coverage percentage alone passes while ``missing`` and the clean-file count sit
on an older run -- which is the shape that let five of eight benchmark
artifacts drift 22 days apart (CLAUDE.md, 1.108.298).

⚠ ``clean_files`` and ``top_10_missing`` are DERIVED here from ``per_file``
rather than read from a summary field, because the artifact does not carry
them. That is the only reason the README can state them at all, and the only
way this test can tell whether it still may.
"""

import json
import re
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parents[1]
_RESULTS = _ROOT / "benchmarks" / "racket_fidelity" / "results.json"
_README = _ROOT / "benchmarks" / "racket_fidelity" / "README.md"
_LANGUAGE_SUPPORT = _ROOT / "LANGUAGE_SUPPORT.md"


@pytest.fixture(scope="module")
def figures() -> dict:
    data = json.loads(_RESULTS.read_text(encoding="utf-8"))
    summary = data["summary"]
    missing_per_file = sorted(
        (len(f["missing"]) for f in data["per_file"]), reverse=True
    )
    return {
        "coverage_pct": summary["source_coverage_pct"],
        "missing": summary["missing"],
        "files": summary["files_measured"],
        "definitions": summary["oracle_source_names"],
        "clean_files": sum(1 for m in missing_per_file if m == 0),
        "top_10_missing": sum(missing_per_file[:10]),
    }


def _reading_the_result(text: str) -> str:
    body = text.split("## Reading the result", 1)
    assert len(body) == 2, "README lost its '## Reading the result' section"
    return body[1].split("\n## ", 1)[0]


def _racket_row(text: str) -> str:
    for line in text.splitlines():
        if line.startswith("| Racket "):
            return line
    raise AssertionError("LANGUAGE_SUPPORT.md lost its Racket row")


def test_language_support_states_the_committed_coverage(figures):
    row = _racket_row(_LANGUAGE_SUPPORT.read_text(encoding="utf-8"))
    stated = re.findall(r"([\d.]+)% of definitions found", row)
    assert stated == [str(figures["coverage_pct"])], (
        f"LANGUAGE_SUPPORT.md's Racket row states {stated}; "
        f"results.json says {figures['coverage_pct']}%"
    )


def test_language_support_states_no_second_coverage_figure(figures):
    """A stale figure left beside the fresh one is the same defect."""
    row = _racket_row(_LANGUAGE_SUPPORT.read_text(encoding="utf-8"))
    percentages = set(re.findall(r"\b(\d+\.\d)%", row))
    assert percentages <= {str(figures["coverage_pct"])}, (
        f"Racket row carries percentages {sorted(percentages)}; only "
        f"{figures['coverage_pct']}% is measured"
    )


@pytest.mark.parametrize(
    "key,template",
    [
        ("definitions", "{:,} definitions"),
        ("files", "across {} files"),
        ("missing", "{} were not found"),
        ("clean_files", "**{} of the "),
        ("top_10_missing", "account for {} of the"),
        ("coverage_pct", '"{}%"'),
    ],
)
def test_readme_restates_the_committed_run(figures, key, template):
    # The README hard-wraps, so a figure is routinely split from its noun by a
    # newline; compare against a whitespace-flattened section.
    section = re.sub(r"\s+", " ", _reading_the_result(_README.read_text(encoding="utf-8")))
    expected = template.format(figures[key])
    assert expected in section, (
        f"README's 'Reading the result' does not state {key}: "
        f"expected {expected!r} from results.json"
    )
